[package]
name = "prismchrono_asm"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] } # Pour l'interface en ligne de commande
thiserror = "1.0" # Pour la gestion des erreurs